### ISSUE TITLE
Does this API solve the proposed use case?

### ISSUE THREAD

**Issue by eanders** [HUD-Data-Lab/Data.Exchange.and.Interoperability#4]
I wanted to start a discussion around who would use this API and if it solves the CE Assessment use case proposed.  

At the moment it doesn't include Coordinated Entry information (specifically assessments and events are not part of the spec) so it seems somewhat lacking for solving data sharing for coordinated entry.  

Additionally, are there any examples of software that collect coordinated entry assessments that would use such an API to push back to HMIS?  Or that might consume an HMIS API to augment their internal client/enrollment concept?

**Comment by CindyNoeUSDS** [comment]
Thanks @eanders, we do need to build out the solve for CE information, and I know @kaungst can propose some approaches to building out the reference so that it can address the use case, along with you and others in the group.

In terms of examples of software that collect CE assessments and would use such an API to push back to HMIS, we know that this is happening (and about to go live) for the Kent County CoC (they worked with WellSky to build out the CE to HMIS API), and we are in conversations with them about this example. We are also looking into potential use of APIs to push either full CE data or partial client data for intake in CoCs that partner with United Way and the 211 call center system to access social services in communities.

In general, we think this use case will be a helpful reference case to for how CoCs using a third party software to collect individual client information can push that to HMIS via API in a transactional, individual client level (rather than a bulk CSV transfer). Part of our task will be communicate and demonstrate the applicability of this reference to other use cases, beyond just coordinated entry.

**Comment by kaungst** [comment]
+1 to the current API spec not being enough to not support CE assessments in full. While we are looking at examples in other communities, would it be correct to say one we know works (albeit inefficiently) is the structure provided by the CSV format specification? I've held off on taking from the existing CSV format specs in favor of the community proposing an alternative.

Do you have any examples or recommendations for resources/endpoints that would achieve the CE assessment use case?

**Comment by eanders** [comment]
@kaungst thanks for adding the 1:1 parity with the HMIS CSV, I think that will help with the use case.  

It looks like https://github.com/HUD-Data-Lab/Data.Exchange.and.Interoperability/issues/7 is covering the ability to find a client.  Thanks!

**Comment by Grant-ICF** [comment]
Circling back to this issue. [ADR 0006](https://github.com/HUD-Data-Lab/Data.Exchange.and.Interoperability/blob/main/doc/adr/0006-Shifting%20from%20Use%20Case%20Focused%20to%20Foundational.md) proposes a conceptual shift of the API Reference to be less use case focused and focus instead on defining the foundational resources of the API Reference. This means that we are focusing on the 1:1 adaptation of the CSV specifications. We acknowledge that this means that the API Reference is more general in nature and may not perfectly solve specific use cases. [ADR 0004](https://github.com/HUD-Data-Lab/Data.Exchange.and.Interoperability/blob/main/doc/adr/0004-use-case-walkthrough.md) seeks to expound on what types of use cases this API Reference can support. 

In addition, we intend to build out a library of optional endpoints to support specific use cases. We are currently seeking out communities to develop case studies to both showcase the use of the API and to also adjust the API to better respond to the needs of communities.
